### PR TITLE
feat(1220): Allow passing scmRepo to some functions

### PR DESCRIPTION
**Pull request by catto**
# Context
I would like to pass cached scmInfo data fetched via `lookupScmUri` but it's a private function. #273 

# Objective
Pass scmRepo instead of scmInfo since lookupScmUri is private function. We can get `scmRepo` from pipeline model (database).

# References
screwdriver-cd/screwdriver#1220

### CODE REVIEW

**Comment by wdstar** [comment]
We should rename test data files.
- scm.getPermissionsWithScmRepo.yaml
- scm.getCommitShaWithScmRepo.yaml

**Comment by yuichi10** [comment]
It looks like affect many code, can we merge this code?

**Comment by catto** [comment]
@yuichi10 It includes only `optional` argument changes. This PR replaces `scmInfo`  but it is added very recently (#273) and there is no running environment because of broken design. Also I'm going to bump minor version.

**Comment by catto** [comment]
@wdstar I forgot to add test data. I fixed it and now files seem to be renamed.

**Comment by catto** [comment]
Following is #277

**Pull request closed without merging**
