### PR TITLE
fix: add key length for mysql

### PR DESCRIPTION
**Pull request by wahapo**
## Context
As it has been accidentally deleted previously, I want bringing it back with this PR.
https://github.com/screwdriver-cd/data-schema/commit/679ed5d26a7c16d44e69ecac149a37bde1007cb2#diff-f9752cf0b76dbe6ff913d5934b1fe45bL41

## References
https://github.com/screwdriver-cd/data-schema/pull/311

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by yoshwata — APPROVED** [review]

**Comment by kumada626** [comment]
There are still some removed `.max()` like these.
https://github.com/screwdriver-cd/data-schema/commit/679ed5d26a7c16d44e69ecac149a37bde1007cb2#diff-8b10593e46d1e61a29919eca7244bfdbL68
https://github.com/screwdriver-cd/data-schema/commit/679ed5d26a7c16d44e69ecac149a37bde1007cb2#diff-79b17d0ddbf5e16fb1a55ed0749a802dL66
https://github.com/screwdriver-cd/data-schema/commit/679ed5d26a7c16d44e69ecac149a37bde1007cb2#diff-39fdef4997aeb94c9c0c684e798fcd3fL42

**Comment by wahapo** [comment]
fixed https://github.com/screwdriver-cd/data-schema/pull/411#issuecomment-692549495

**Review by kumada626 — APPROVED** [review]

**Review by ibu1224 — APPROVED** [review]

**Review by tkyi — APPROVED** [review]

**Comment by tkyi** [comment]
Does this PR not handle this issue?
https://github.com/screwdriver-cd/data-schema/pull/280

**Comment by wahapo** [comment]
Oh, because of the `valids`, it has always been a success.
https://github.com/screwdriver-cd/data-schema/blob/679ed5d26a7c16d44e69ecac149a37bde1007cb2/test/models/index.test.js#L59

This should probably be fine.

**Review by tkyi — APPROVED** [review]

**Pull request merged**
