### PR TITLE
fix(2053): [1] add RESERVED_JOB_ANNOTATIONS and RESERVED_PIPELINE_ANNOTATIONS

### PR DESCRIPTION
**Pull request by wahapo**
## Context
Add feature of https://github.com/screwdriver-cd/screwdriver/issues/2053

## References
https://github.com/screwdriver-cd/screwdriver/issues/2053

[1] https://github.com/screwdriver-cd/data-schema/pull/414 (this PR)
[2] https://github.com/screwdriver-cd/config-parser/pull/111
UI: https://github.com/screwdriver-cd/ui/pull/605

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by tkyi — APPROVED** [review]

**Review by ibu1224 — APPROVED** [review]

**Comment by wahapo** [comment]
As I noticed in the [test](https://github.com/screwdriver-cd/config-parser/blob/06bf44a884d73ed2636df3ae8500e000116ee6e9/test/index.test.js#L506-L515), `buildCluster` seems to support not only Job-Level, but also Pipeline-Level.
https://github.com/screwdriver-cd/models/blob/2005785b9ac30ec7992914098924596f41212794/lib/helper.js#L134-L140

**Comment by tkyi** [comment]
Hmm seems weird to allow it in both; not seeing it in the documentation too
@parthasl is this intentional?

**Comment by parthasl** [comment]
> Hmm seems weird to allow it in both; not seeing it in the documentation too
> @parthasl is this intentional?

yes, all jobs under that pipeline should route to same build cluster, if build cluster is active.

**Comment by parthasl** [comment]
build cluster annotation is supported for both Pipeline and Job. If Pipeline level annotation is not available, we update pipeline build cluster based on the cluster weightage %. Pipeline level build cluster annotation is needed for disk-based cache feature.

**Comment by wahapo** [comment]
So that's the expected behavior. This is able to separate issue from this PR itself, Let's proceed with this PR fix.

@parthasl Could you please add to the pipeline annotations in the guide later? I wasn't sure why 'Pipeline level build cluster annotation' was needed for the disk-based cache, , so I can't describe it well.

**Review by yoshwata — APPROVED** [review]

**Review by kumada626 — APPROVED** [review]

**Pull request merged**
