### PR TITLE
Labels are throwing off the validator, removing them

### PR DESCRIPTION
**Pull request by stjohnjohnson**
For complex structures like the config, label isn't helping. It's saying Job is broken instead of "main"

With labels:
```js
const Joi = require('joi');
const stepSchema = Joi.string().alphanum().label('Step');
const stepsSchema = Joi.object().keys({
    init: stepSchema,
    test: stepSchema,
    publish: stepSchema
}).label('List of Steps');

const example = {
    init: 'foo',
    test: 'BAD-THINGS_HERE!!!',
    publish: 'bar'
};
Joi.validate(example, stepsSchema).error.toString();
// 'ValidationError: child "Step" fails because ["Step" must only contain alpha-numeric characters]'
```

Without labels:
```js
const Joi = require('joi');
const stepSchema = Joi.string().alphanum();
const stepsSchema = Joi.object().keys({
    init: stepSchema,
    test: stepSchema,
    publish: stepSchema
});

const example = {
    init: 'foo',
    test: 'BAD-THINGS_HERE!!!',
    publish: 'bar'
};
Joi.validate(example, stepsSchema).error.toString();
// 'ValidationError: child "test" fails because ["test" must only contain alpha-numeric characters]'
```

### CODE REVIEW

**Comment by FenrirUnbound** [comment]
So if I'm understanding this correctly, it's using the label "Job". And because it's using the label, it the error too vague.

This may lead us into a longer conversation, and we can table it if it comes to it. Since you're proposing to remove the labels, how would the validator determine which job is the problematic one?

**Comment by stjohnjohnson** [comment]
@FenrirUnbound Great point!  In my haste last night I completely gave way too little context here.  I've updated the description with a chunk of code to reproduce the problem I encountered.

**Comment by d2lam** [comment]
👍 Makes sense

**Comment by FenrirUnbound** [comment]
Thanks for the clarification!

👍  Looks great to me

jkepuv9

**Pull request merged**
