### PR TITLE
Storing Workflow in Pipeline

### PR DESCRIPTION
**Pull request by stjohnjohnson**
Pipeline should have the latest state of the workflow stored.

### CODE REVIEW

**Comment by d2lam** [comment]
"Replace"? You mean we remove the admins field too?

**Comment by stjohnjohnson** [comment]
@d2lam I'll split out the admin change for another PR.  Let's focus on the stuff needed for Friday.

**Comment by d2lam** [comment]
LGTM 👍

**Comment by FenrirUnbound** [comment]
👍 

tumblr_oc99aybl7c1toe0eco1_500

**Pull request merged**
