### PR TITLE
Add a property containing a list of all the keys in the model

### PR DESCRIPTION
**Pull request by petey**
Since our models should be a representation of a database row, it sure would be nice to be able to get all the field names.

### CODE REVIEW

**Comment by nkatzman** [comment]
Where do we plan on using this field?

**Comment by petey** [comment]
@nkatzman The base model should be able to take in the return data from datastore.* and convert that to the keys in the model. In order to do that, it needs to know what those keys are.

**Comment by stjohnjohnson** [comment]
👍 
mrw_i_visit_a_new_sub_and_sort_by_top_all_time

**Comment by FenrirUnbound** [comment]
👍 

kdkhgx6

**Pull request merged**
