### PR TITLE
Removing Platforms until we come up with the Template design

### PR DESCRIPTION
**Pull request by stjohnjohnson**
Since we're certainly not going to be adding the concept of "platforms" and instead going to replace it with "templates", let's just remove all the Platform code and simplify the interfaces.

### CODE REVIEW

**Comment by d2lam** [comment]
👍

**Comment by d2lam** [comment]
👍

**Comment by d2lam** [comment]
Need to change dynamo-datastore as well 
https://github.com/screwdriver-cd/datastore-dynamodb/blob/master/index.js#L11

And delete the table.

**Comment by nkatzman** [comment]
bump version please

**Comment by nkatzman** [comment]
👍

**Pull request merged**
